#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          0

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config click_to_focus       true

# MONITORS
if [[ $(hostname) == "lewisDesktop" ]]; then
  # Desktop
  xrandr --output DP-0 --auto --pos 0x240 --output HDMI-0 --auto --pos 3440x0
  bspc monitor DP-0 -d 1 2 3 4 5
  bspc monitor HDMI-0 -d 6 7 8 9 10
elif [[ $(hostname) == "lewisLaptop" ]]; then
  # Laptop
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

feh --bg-center ~/.config/wallpaper

# COLOURS
bspc config normal_border_color   "#757575" #"#039BE5"
bspc config active_border_color   "#757575" #"#039BE5"
bspc config focused_border_color  "#FB8C00"
bspc config presel_feedback_color "#757575"

# RULES
bspc rule -a Mullvad state=floating
bspc rule -a Lightscreen state=floating
bspc rule -a Wicd-client.py state=floating
bspc rule -a Alacritty state=floating
bspc rule -a "Firefox Beta" state=tiled
if [[ $(hostname) == "GLaDOS" ]]; then
  # Desktop
  bspc rule -a Spotify desktop=^6
  bspc rule -a Nautilus state=floating rectangle=1024x576+1208+432
else
  # Laptop
  bspc rule -a Nautilus state=floating rectangle=1024x576+448+252
fi

bash $HOME/.config/polybar/launch.sh

setxkbmap -layout gb
setxkbmap -option caps:escape
xsetroot -cursor_name left_ptr

xset -dpms
xset s off

wmname LG3D
