#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          0

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config click_to_focus       true

# MONITORS
# <xrandr settings for monitors>

# DESKTOPS
# <bspc monitor settings>

feh --bg-center ~/.config/wallpaper

# COLOURS
bspc config normal_border_color   "#757575"
bspc config active_border_color   "#757575"
bspc config focused_border_color  "#6441A4"
bspc config presel_feedback_color "#757575"

# RULES
bspc rule -a Mullvad state=floating
bspc rule -a Lightscreen state=floating
bspc rule -a Wicd-client.py state=floating
bspc rule -a Alacritty state=floating
# <computer specific rules>

bash $HOME/.config/polybar/launch.sh

setxkbmap -layout gb
setxkbmap -option caps:escape
xsetroot -cursor_name left_ptr

xset -dpms
xset s off

wmname LG3D
