#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          0

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config click_to_focus       true

# MONITORS
if [[ $(hostname) == "GLaDOS" ]]; then
  xrandr --output DP-0 --auto --pos 0x220 --output HDMI-0 --auto --pos 3440x0
  bspc monitor DP-0 -d I II III IV V
  bspc monitor HDMI-0 -d VI VII VIII IX X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

feh --bg-center ~/.config/wallpaper

# COLOURS
bspc config normal_border_color   "#039BE5"
bspc config active_border_color   "#039BE5"
bspc config focused_border_color  "#FB8C00"
bspc config presel_feedback_color "#757575"

# RULES
bspc rule -a Mullvad state=floating

$HOME/.config/polybar/launch.sh

setxkbmap -layout gb
setxkbmap -option caps:escape
xsetroot -cursor_name left_ptr

xset -dpms
xset s off

wmname LG3D
