#! /bin/sh

sxhkd &

# bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          0

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config click_to_focus       true

feh --bg-center ~/.config/wallpaper

# MONITORS
if [[ $(hostname) == "GLaDOS" ]]; then
  # bspc monitor DP-0 -d I II III IV V
  # bspc monitor HDMI-0 -d VI VII VIII IX X
  bspc monitor -d I II III IV V VI VII VIII IX X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

# COLOURS
bspc config normal_border_color   "#1976D2"
bspc config active_border_color   "#1976D2"
bspc config focused_border_color  "#F57C00"
bspc config presel_feedback_color "#7CB342"

# RULES
bspc rule -a Mullvad state=floating

$HOME/.config/polybar/launch.sh

setxkbmap -layout gb
xsetroot -cursor_name left_ptr
xset -dpms
